---
collections:
  - name: ansible.posix  # Required for profile_tasks callback plugin.
  - name: ansible.windows
    version: '>=2.0.0'
  - name: community.docker
  - name: community.general  # Required for from_ini and supervisorctl modules.
    version: '>=10.6.0'  # Required by community.general.from_ini filter.
  - name: community.windows
    version: '>=2.0.0'
roles:
  - name: ea31337.metatrader
    scm: git
    src: https://github.com/EA31337/ansible-role-metatrader.git
    version: master
  - name: ea31337.wine
    scm: git
    src: https://github.com/EA31337/ansible-role-wine.git
    version: v1.0.4
  - name: ea31337.xvfb
    scm: git
    src: https://github.com/EA31337/ansible-role-xvfb.git
    version: v1.0.4
