# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
collections:
  - name: community.general  # For unixy.
roles:
  - name: ea31337.metatrader
    scm: git
    src: https://github.com/nseam/ansible-role-metatrader.git
    version: test/testing-after-wine-role-changes
