---
- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: ea31337.mt_runner
      no_log: '{{ ansible_verbosity | default(0) < 1 }}'
      vars:
        # noqa: var-naming[no-role-prefix]
        metatrader_version: 5
        mt_runner_bt_mt5_config:
          Common:
            Login: "{{ lookup('env', 'MT_RUNNER_MT5_LOGIN') | default('12345', true) }}"
            Password: "{{ lookup('env', 'MT_RUNNER_MT5_PASSWORD') | default('SETME', true) }}"
            Server: "{{ lookup('env', 'MT_RUNNER_MT5_SERVER') | default('MetaQuotes-Demo', true) }}"
          Tester:
            Deposit: 10000
            ExecutionMode: 0
            Expert: EA31337-Libre-v1.013.ex5
            FromDate: 2024.01.01
            Leverage: 1:500
            Login: "{{ lookup('env', 'MT_RUNNER_MT5_LOGIN') | default('12345', true) }}"
            Model: 1
            Report: report.html
            ReplaceReport: 1
            ShutdownTerminal: 1
            Symbol: EURUSD
            ToDate: 2024.01.11
        mt_runner_get_url_list:
          - dest: '{{ mt_runner_mt_path }}/MQL5/Experts'
            url: https://github.com/EA31337/EA31337-Libre/releases/download/v1.013/EA31337-Libre-v1.013.ex5
