---
name: Molecule

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - mt4
          - mt5-ea
    steps:
      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
      - uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
      - name: Install required tools
        run: |
          sudo apt update
          sudo apt install -y x11-apps imagemagick
      - name: Start background screenshot loop
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p screenshots
          echo "Starting screenshot loop..."
          while true; do
            sleep 120
            TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
            SCREENSHOT_FILE="screenshots/latest_screenshot.png"

            # Take screenshot
            DISPLAY=:0 xwd -root -out temp_screenshot.xwd || true
            convert temp_screenshot.xwd "$SCREENSHOT_FILE"  || true
            rm temp_screenshot.xwd  || true

            if [ -f "$SCREENSHOT_FILE" ]; then
              # Commit latest screenshot with amend
              git add "$SCREENSHOT_FILE"
              git commit --amend -m "Update latest screenshot taken at $TIMESTAMP"
              git push --force-with-lease
            fi
          done &
      - uses: gofrolist/molecule-action@v2
        env:
          ANSIBLE_FORCE_COLOR: '1'
          ANSIBLE_STDOUT_CALLBACK: yaml
          MT_RUNNER_MT4_LOGIN: ${{ secrets.MT_RUNNER_MT4_LOGIN || '12345' }}
          MT_RUNNER_MT4_PASSWORD: ${{ secrets.MT_RUNNER_MT4_PASSWORD || 'SETME' }}
          MT_RUNNER_MT5_LOGIN: ${{ secrets.MT_RUNNER_MT5_LOGIN || '12345' }}
          MT_RUNNER_MT5_PASSWORD: ${{ secrets.MT_RUNNER_MT5_PASSWORD || 'SETME' }}
        with:
          molecule_args: --scenario-name ${{ matrix.scenario }}
          molecule_command: test
          molecule_options: --verbose
          molecule_working_dir: "${{ github.repository }}"
      - if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
    timeout-minutes: 20
